version: '3'

volumes:
  vlpg-vol:

services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - vlpg-vol:/var/lib/postgresql/data

  viztube:
    image: vizlegal/viztube:dev-2019.10.25-r2
    command: server
    volumes:
      - .:/app
    ports:
      - "3000:4000"
    links:
      - "postgres"
    depends_on:
      - postgres
    environment:
      - MIX_ENV=dev
      - DB_HOSTNAME=postgres
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - GUARDIAN_SECRET_KEY=${GUARDIAN_SECRET_KEY}
      - LOCAL_DEV="true"
      - VERBOSE="true"
